{
 "title": "Stats from Python examples",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Stats from Python: Example 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "socket_listener",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "socket_listener",
     "select": [
      [
       { "params": [ "value2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats from Python code: Example 2 and 4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "format" ], "type": "tag" }
     ],
     "measurement": "good_metric_name",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "format" ], "type": "tag" }
     ],
     "measurement": "good_metric_name",
     "select": [
      [
       { "params": [ "value2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats from Python: Example 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "prefix_metric_name.value1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "prefix_metric_name.value2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}